services:

  db:
<<<<<<< HEAD
<<<<<<< HEAD
    container_name: ${SPENNY_DB_CONTAINER_NAME}
    image: ${SPENNY_DB_IMAGE_NAME}
    hostname: ${SPENNY_DB_HOST}
    volumes:
<<<<<<< HEAD
      - /home/hcheong/Desktop/Other/SIDE_PROJECTS/spenny/utils/test_spenny_db.sql:/docker-entrypoint-initdb.d/init.sql 
=======
    env_file:
      - demo.env
=======
>>>>>>> 2e77600 (Fixed up docker file and begin writing bucket execution)
    container_name: ${SPENNY_DB_CONTAINER_NAME}
    image: ${SPENNY_DB_IMAGE_NAME}
    hostname: ${SPENNY_DB_HOST}
<<<<<<< HEAD
>>>>>>> 856337b (Moving to docker compose)
=======
    volumes:
<<<<<<< HEAD
      - ${SPENNY_DB_SQL_DUMP_FILE_PATH}:/docker-entrypoint-initdb.d/init.sql 
>>>>>>> 385cba1 (Updated docker compose to use test SQL)
=======
      - /home/hcheong/Desktop/Other/spenny/utils/test_spenny_db.sql:/docker-entrypoint-initdb.d/init.sql 
>>>>>>> 2e77600 (Fixed up docker file and begin writing bucket execution)
=======
      - /home/hcheong/projects/spenny/utils/test_spenny_db.sql:/docker-entrypoint-initdb.d/init.sql 
>>>>>>> a5b6c15 (Updated env to the local path + docker compose pathing)
    ports:
      - ${SPENNY_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${SPENNY_DB_USER}
      - POSTGRES_PASSWORD=${SPENNY_DB_PASS}
      - POSTGRES_DB=${SPENNY_DB_NAME}
      - TZ=${SPENNY_DB_TIMEZONE} 
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 92e98b1 (Added profiles for startup and added new test env)
    profiles:
    - test
    - demo

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    image: ${BACKEND_IMAGE_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile

=======

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    image: ${BACKEND_IMAGE_NAME}
<<<<<<< HEAD
    build: ${BACKEND_APP_PATH}
>>>>>>> 856337b (Moving to docker compose)
=======
    build:
      context: ./backend
      dockerfile: Dockerfile

>>>>>>> 2e77600 (Fixed up docker file and begin writing bucket execution)
    ports:
      - ${BACKEND_PORT}:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPENNY_DB_USER=${SPENNY_DB_USER}
      - SPENNY_DB_PASS=${SPENNY_DB_PASS}
      - SPENNY_DB_NAME=${SPENNY_DB_NAME}
      - SPENNY_DB_HOST=${SPENNY_DB_HOST}
      - SPENNY_DB_PORT=${SPENNY_DB_PORT}
      - TZ=${SPENNY_DB_TIMEZONE}
    volumes:
      - ${BACKEND_APP_PATH}/app:/app
<<<<<<< HEAD
<<<<<<< HEAD
    profiles:
    - demo
    - live

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    image: ${FRONTEND_IMAGE_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:5173
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - BACKEND_CONTAINER_URL=${BACKEND_CONTAINER_URL}
      - TZ=${FRONTEND_TIMEZONE}
    volumes:
      - ${FRONTEND_APP_PATH}:/app
    profiles:
    - demo
    - live
=======
>>>>>>> 856337b (Moving to docker compose)
=======
    profiles:
    - demo
    - live
>>>>>>> 92e98b1 (Added profiles for startup and added new test env)
