services:

  db:
    container_name: ${SPENNY_DB_CONTAINER_NAME}
    image: ${SPENNY_DB_IMAGE_NAME}
    hostname: ${SPENNY_DB_HOST}
    ports:
      - ${SPENNY_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${SPENNY_DB_USER}
      - POSTGRES_PASSWORD=${SPENNY_DB_PASS}
      - POSTGRES_DB=${SPENNY_DB_NAME}
      - TZ=${SPENNY_DB_TIMEZONE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s